### PR TITLE
Implemented BitSet#clearFrom to allow for _length adjustment

### PR DESCRIPTION
**Pull request by djspiewak**
This should fix the memory leak reported by @alissapajer

### CODE REVIEW

**Comment by alissapajer** [comment]
Testing this against the original bug with versions
slamx: `12.5.19 `
s3: `10.0.6`
quasar: `91.2.5-4e6f190`

**Comment by alissapajer** [comment]
@djspiewak  🐼

I'll get a new heap dump and link it in the story.
```
java.lang.OutOfMemoryError: Java heap space
        at quasar.precog.BitSet.copy(BitSet.java:232)
        at quasar.precog.util.BitSetUtil$BitSetOperations$.$amp$extension(BitSetUtil.scala:30)
        at quasar.yggdrasil.table.cf.util$$anonfun$filter$1$$anon$37.<init>(Util.scala:723)
        at quasar.yggdrasil.table.cf.util$$anonfun$filter$1.applyOrElse(Util.scala:723)
        at quasar.yggdrasil.table.cf.util$$anonfun$filter$1.applyOrElse(Util.scala:718)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)
        at quasar.yggdrasil.table.CF1P$$anon$17.apply(CFN.scala:84)
        at quasar.yggdrasil.table.ColumnarTableModule$ColumnarTable.$anonfun$leftShift$15(ColumnarTableModule.scala:1476)
        at quasar.yggdrasil.table.ColumnarTableModule$ColumnarTable$$Lambda$4621/1042825088.apply(Unknown Source)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$Lambda$131/1414649263.apply(Unknown Source)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:225)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:432)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:432)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:432)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at quasar.yggdrasil.table.ColumnarTableModule$ColumnarTable.leftShiftUnfocused$1(ColumnarTableModule.scala:1474)
        at quasar.yggdrasil.table.ColumnarTableModule$ColumnarTable.$anonfun$leftShift$23(ColumnarTableModule.scala:1575)
        at quasar.yggdrasil.table.ColumnarTableModule$ColumnarTable$$Lambda$4604/920164063.apply(Unknown Source)
        at scalaz.StreamT.$anonfun$map$4(StreamT.scala:101)
        at scalaz.StreamT$$Lambda$1443/2106703227.apply(Unknown Source)
        at scalaz.StreamT$Yield$$anon$7.apply(StreamT.scala:335)
        at scalaz.StreamT.$anonfun$map$1(StreamT.scala:103)
        at scalaz.StreamT$$Lambda$1442/672197341.apply(Unknown Source)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1$$Lambda$115/2012042176.apply(Unknown Source)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1$$Lambda$115/2012042176.apply(Unknown Source)
        at cats.effect.IO$Map.apply(IO.scala:1407)
        at cats.effect.IO$Map.apply(IO.scala:1403)
```

**Comment by alissapajer** [comment]
I ran it again to get the heap dump, and it hit the 10min timeout, which has since been fixed in s3. So I'm updating s3 and slamx versions and trying again. The first time I didn't hit the timeout though; it's possible the OOM happens right around 10min.

**Comment by djspiewak** [comment]
Yeah I definitely need a heap dump. Could be a new issue

**Comment by alissapajer** [comment]
Ran it a third time with versions
s3: `11.0.2`
slamx: `12.7.8`
quasar: `91.2.5-4e6f190`
and it OOM'd at 2min. I don't have an explanation for why this could be nondeterministic yet; I'm going to let it run a few times to see if really it sometimes doesn't OOM.

**Comment by alissapajer** [comment]
I haven't been able to make it _not_ OOM again, so I'm going to assume it was user error.

**Comment by alissapajer** [comment]
@djspiewak do you have a preference:
1) Deassociate ch3805 and merge this
2) Don't merge this until we've figured out why it's still OOMing

**Comment by djspiewak** [comment]
@alissapajer It entirely depends on the heap dump. Can you link here and we'll decide if it's the same bug or a new one?

**Comment by alissapajer** [comment]
@djspiewak it's linked in the story.

**Comment by djspiewak** [comment]
@alissapajer I've disassociated this PR from the issue. I think it would still be good to land, but it doesn't affect the OOM.

**Pull request merged**
