### PR TITLE
In ExpandShifts also repair when focus is undefined

### PR DESCRIPTION
**Pull request by rintcius**

### CODE REVIEW

**Comment by rintcius** [comment]
[ch 183]

**Comment by rintcius** [comment]
[ch183]

**Comment by djspiewak** [comment]
@rintcius There are conflicts now, but I'm pretty sure that the build errors are also legitimate (which is why I've held off on merging).

**Comment by rintcius** [comment]
@djspiewak yeah, it's difficult to say for sure with no error output, but I have just pushed a commit based on a guess that one of the tests times out. 

If this is the case we should look into fixing this: the test should timeout and fail before the whole build times out.

**Pull request merged**
