### PR TITLE
Build cleanup

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by alissapajer** [comment]
We publish test artifacts so technically this is `breaking`. I want to make it `revision` though.

**Comment by alissapajer** [comment]
Oh interesting. Build failed because we're running
```
      "testOnly -- failtrace" \
      "exclusive:testOnly -- failtrace"
```
in Travis. Do we still care about the `exclusive` variant?

**Comment by djspiewak** [comment]
Ehhhh. I guess I'm okay with that. SDBE's tests might break, but it'll probably be okay.

**Comment by alissapajer** [comment]
I mean, `breaking` is technically correct, so I won't object :)

**Pull request merged**
