### PR TITLE
Use quasar.api.table.TableColumn instead of custom type in destination API

### PR DESCRIPTION
**Pull request by jsantos17**
[ch7279]

### CODE REVIEW

**Comment by alissapajer** [comment]
@jsantos17 a couple compile errors

**Comment by jsantos17** [comment]
@alissapajer this should be ready for another look.

**Comment by alissapajer** [comment]
@jsantos17 we're changing the API that quasar's exposing, so technically this should be **breaking**.

**Comment by jsantos17** [comment]
@alissapajer makes sense! Even if no-one is using this API just yet.

**Pull request merged**
