### PR TITLE
Add snippet to confirm we are using Travis' premium VMs

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by alissapajer** [comment]
Travis sent me this to include in our `.travis.yml` file.

**Comment by nicflores** [comment]
@alissapajer, we aren't merging this, correct? This is just to double check the output of `nproc`.

**Comment by alissapajer** [comment]
@nicflores I'd like to merge this. That way we can always confirm that we are on premium VMs.

**Comment by alissapajer** [comment]
This is hitting an unrelated SOE that was introduced recently, but that I've seen in other builds.

**Comment by alissapajer** [comment]
@nicflores green!

**Pull request merged**
