### PR TITLE
Added forking to all the things, as it should have been

### PR DESCRIPTION
**Pull request by djspiewak**

### CODE REVIEW

**Comment by edmundnoble** [comment]
I suggest that in addition to this, we add all of `.jvmopts` into the `javaOptions` key.

**Comment by djspiewak** [comment]
Oh that's definitely worth doing. I'll take care of that quickly…

**Comment by edmundnoble** [comment]
Hmmm I suppose this is good for now though eventually we may want different JVM options for SBT itself and the forked tasks.

**Comment by djspiewak** [comment]
Don't merge this yet. Terrible things are happening

**Comment by edmundnoble** [comment]
Perhaps we should only merge this after the fixed specs2 version is available?

**Comment by djspiewak** [comment]
@edmundnoble Agreed

**Comment by alissapajer** [comment]
@djspiewak there is here that possibly needs to change https://github.com/slamdata/quasar/blob/master/build.sbt#L502-L505

**Comment by djspiewak** [comment]
@alissapajer Oh crap, yes. That's not what's causing the mongoIt failure though (I know what is, I just haven't fixed it yet).

**Comment by djspiewak** [comment]
[ch270]

**Comment by djspiewak** [comment]
Closing. I'll loop back to this someday soon.

**Pull request closed without merging**
