### PR TITLE
Incremenal RValue parse instruction interpreter

### PR DESCRIPTION
**Pull request by wemrysi**
[ch4995]

### CODE REVIEW

**Comment by wemrysi** [comment]
5b310bb is the semantic changes, 7bb4d52 is some code reorg so I recommend only viewing the diff for the first commit.

**Comment by alissapajer** [comment]
@wemrysi have you run the mimir `RValue`-backed integration tests against this change? If not, I think we can still merge and see what happens :) If something failed we'd have to iterate back here in either case.

**Comment by wemrysi** [comment]
@alissapajer am doing so now! I'll push the fix for `chunksPerJob` if everything looks good.

**Comment by wemrysi** [comment]
@alissapajer local run of the `it` tests were green :+1:

**Pull request merged**
