### PR TITLE
Upgraded to specs2 4.1.2

### PR DESCRIPTION
**Pull request by djspiewak**
Should fix the SOE in tests.

### CODE REVIEW

**Comment by djspiewak** [comment]
[ch270]

**Comment by alissapajer** [comment]
[ch270]

**Comment by alissapajer** [comment]
Dangit I lost the race by a second!

**Comment by djspiewak** [comment]
Type faster. :-D

**Comment by alissapajer** [comment]
@djspiewak if you see this green before I do feel free to merge.

**Pull request merged**
