### PR TITLE
Delete DeadEnd

### PR DESCRIPTION
**Pull request by alissapajer**
Also not sure the last time it was in use.

Depends on #3957

### CODE REVIEW

**Comment by jsantos17** [comment]
@alissapajer conflicts!

**Comment by alissapajer** [comment]
Oh and the reducers/buckets commits also ended up here... clearly I'm not paying attention to what branch I'm on...

**Comment by alissapajer** [comment]
@jsantos17 merged in master.

**Comment by jsantos17** [comment]
>Oh and the reducers/buckets commits also ended up here.

@alissapajer just checked this and looks like we have some non-deadend related changes:

```
~/R/s/quasar-other ❯❯❯ git log  master..dead-end
commit 908c7b7404e4642c88f6bd305a538bab4f1cf4c0 (HEAD -> dead-end, alissa/dead-end)
Merge: c83920376f da408d2ae8
Author: Alissa Pajer <alissa.pajer@gmail.com>
Date:   Mon Nov 19 18:01:18 2018 -0700

    Merge remote-tracking branch 'upstream/master' into dead-end

commit c83920376f304cc99e62d8f006672baae477c373
Author: Alissa Pajer <alissa.pajer@gmail.com>
Date:   Mon Nov 19 16:35:43 2018 -0700

    Delete a couple unused bits from Coalesce

commit cab6da192dc85116ee3c4549114832a9b9eed638
Author: Alissa Pajer <alissa.pajer@gmail.com>
Date:   Mon Nov 19 16:28:19 2018 -0700

    Remove qscript rewrite deleting unused reducers

commit da775abd18ea863782fa091c5391d0683bc46ec9
Author: Alissa Pajer <alissa.pajer@gmail.com>
Date:   Mon Nov 19 16:27:53 2018 -0700

    Remove qscript rewrite deleting duplicate reducers/buckets

commit 2ef80db9d30c546e5c51c1dec1eb79a848df0eb7
Merge: b88700690a 8ee60e7768
Author: Alissa Pajer <alissa.pajer@gmail.com>
Date:   Mon Nov 19 16:02:05 2018 -0700

    Merge remote-tracking branch 'upstream/master' into dead-end

commit b88700690a5b1e562deaad5e8adb3281b39ade78
Author: Alissa Pajer <alissa.pajer@gmail.com>
Date:   Mon Nov 19 16:00:52 2018 -0700

    Remove DeadEnd
```

Were those intended?

**Comment by alissapajer** [comment]
@jsantos17 yes they were intended. Is it okay that they landed?

**Comment by jsantos17** [comment]
@alissapajer yep! Just double checking.

**Pull request merged**
