### PR TITLE
Downgrade to fs2-0.10.5 and cats-effect-0.10.1

### PR DESCRIPTION
**Pull request by wemrysi**
These are compatible with the versions that `http4s` uses.

### CODE REVIEW

**Comment by wemrysi** [comment]
[ch363]

**Comment by djspiewak** [comment]
@wemrysi Are those integration test link errors legit? Or just incremental compilation failing us… again…

**Comment by wemrysi** [comment]
@djspiewak Ugh, might be legit as I don't think I ran the regression tests locally. Will take a look.

**Comment by wemrysi** [comment]
@djspiewak So looks like these errors are probably due to caching as I don't see them locally, however a couple of the time-related `lwc_local` regression tests fail, which I don't really understand. Going to merge from `master` and try agian.

**Pull request merged**
