### PR TITLE
Minor tables fixes

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by alissapajer** [comment]
I made this `breaking` because of the `TableRefNameField` change.

**Comment by alissapajer** [comment]
Nothing's depending on it yet, so we could stick with `revision` if the first version of sdbe to use `DefaultTables` will use this PR.

**Comment by wemrysi** [comment]
@alissapajer Yeah, `revision` is probably fine, I can depend on this version over in sdbe.

**Comment by alissapajer** [comment]
@wemrysi oops I pushed the `PreparationEvent` commit to this branch. I meant to push to a new branch and make a new PR.

**Comment by wemrysi** [comment]
@alissapajer no worries, let's just change the version to `feature`.

**Pull request merged**
