### PR TITLE
Use default settings for ProxySearch

### PR DESCRIPTION
**Pull request by jsantos17**
I have confirmed this works with the frontend. [Green frontend build here](https://travis-ci.com/slamdata/slamx/builds/131846875).

@djspiewak I have replaced the proxy-vole configuration with the defaults. Would you mind explaining the rationale used to pick the defaults we had before this PR?

### CODE REVIEW

**Comment by jsantos17** [comment]
[ch9579]

**Comment by rintcius** [comment]
Good to verify that this works on all platforms, but I prefer this way of configuration. If this turns out to be not working on some platform, then I'd rather fix it upstream (if necessary by forking the proxy-vole repos).

FYI we are using this now: https://github.com/MarkusBernhardt/proxy-vole/blob/4dfc7d0e8c664ff9051284093c500d7aa6a4bfe0/src/main/java/com/github/markusbernhardt/proxy/ProxySearch.java#L99-L124 - note that according to the javadoc this should be suitable for every platform, so if it turns out there's a problem on some platform we can consider it a bug in proxy-vole.

**Comment by rintcius** [comment]
Leaving it open to give @djspiewak a chance to answer @jsantos17 's question and review too.

**Comment by djspiewak** [comment]
@jsantos17 Those selectors were basically the result of testing on each platform and figuring out which configuration found the appropriate settings. I'm totally fine changing this back to the defaults as you've done, I just want to make sure it works and finds the system configurations. Let's merge this for now and test.

**Pull request merged**
