### PR TITLE
Removed hoarder

### PR DESCRIPTION
**Pull request by djspiewak**
I've confirmed locally that hoarder cannot handle quasar for some reason. I'm not sure why, but it appears to be the case. Fortunately, @nicflores's S3 stuff should ensure that we're not completely bonkers on build times, but it's going to be unfortunate. The PR compilation stage will always be from scratch now. *grumble grumble grumble*

### CODE REVIEW

**Comment by alissapajer** [comment]
We should also update the `scripts/s3cache` script so that it doesn't upload/download the hoarder artifacts.

**Comment by alissapajer** [comment]
@djspiewak travis compile staged failed with our good old friend the scalac SOE. I'll let you restart the build.

**Comment by nicflores** [comment]
@alissapajer and @djspiewak, I can update the s3cache script to not include hoarder.

**Comment by alissapajer** [comment]
@nicflores that was already done in a8657cb

**Comment by nicflores** [comment]
@djspiewak, yep, just saw the commit! thanks Daniel.

**Pull request merged**
