### PR TITLE
Improve performance of Provenance#projectStatic

### PR DESCRIPTION
**Pull request by wemrysi**

### CODE REVIEW

**Comment by alissapajer** [comment]
Is this to address that query that took 25 minutes to compile? Do we have a ticket for that?

**Comment by wemrysi** [comment]
@alissapajer yes and yes, but unfortunately this doesn't fix the problem, even though it is still an improvement. 7927 is one of the issues and has a link to the other.

**Comment by alissapajer** [comment]
The build hung. I don't think we've been experiencing hung quasar builds in master? So it could be related to this PR.

**Comment by wemrysi** [comment]
@alissapajer Looks like travis was having some issues, going to restart.

**Comment by wemrysi** [comment]
@alissapajer I've managed to reproduce the hang locally, investigating.

**Comment by wemrysi** [comment]
I haven't had time to track down the issue, closing for now.

**Pull request closed without merging**
