### PR TITLE
Upgrade specs2 and scalacheck dependencies

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by alissapajer** [comment]
There's a new scalacheck generator I want to use.

**Comment by alissapajer** [comment]
I was pretty sure something was going to explode at runtime :smile: 

I'm going to make this a WIP PR so I can rebase it to get the fixes into the same commit as the upgrades.

**Comment by alissapajer** [comment]
@djspiewak this is ready, pending Travis. It's based on #3625 because I needed that `scalaz` version.

@wemrysi if you end up rebasing #3625 (I only say that because it looks like it's not building), no problem, I can just cherry-pick this commit over.

**Comment by djspiewak** [comment]
@alissapajer I think the build failures are legit.

**Comment by alissapajer** [comment]
Grr, I agree they look legit, but after merging in #3625 I had those tests passing locally. Lemme clear the cache and try again.

**Comment by djspiewak** [comment]
@alissapajer Merge conflicts

**Pull request merged**
